AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
        BucketName: "iwasa-patch-report-bucket"

  SNSTopic:
    Type: "AWS::SNS::Topic"
    Properties:
        DisplayName: "iwasa-patch-report-topic"
        TopicName: "iwasa-patch-report-topic"

  SNSTopicPolicy:
    Type: "AWS::SNS::TopicPolicy"
    Properties:
        PolicyDocument: !Sub "{\"Version\":\"2008-10-17\",\"Id\":\"__default_policy_ID\",\"Statement\":[{\"Sid\":\"__default_statement_ID\",\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"*\"},\"Action\":[\"SNS:GetTopicAttributes\",\"SNS:SetTopicAttributes\",\"SNS:AddPermission\",\"SNS:RemovePermission\",\"SNS:DeleteTopic\",\"SNS:Subscribe\",\"SNS:ListSubscriptionsByTopic\",\"SNS:Publish\",\"SNS:Receive\"],\"Resource\":\"${SNSTopic}\",\"Condition\":{\"StringEquals\":{\"AWS:SourceOwner\":\"${AWS::AccountId}\"}}}]}"
        Topics: 
          - !Ref SNSTopic

  SNSSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
        TopicArn: !Ref SNSTopic
        Endpoint: "iwasa.takahito@classmethod.jp"
        Protocol: "email"
        Region: !Ref AWS::Region

  EventsRule:
    Type: "AWS::Events::Rule"
    Properties:
      Name: "AWS-SystemsManager-PatchManager-PatchReport-iwasa-patch-report"
      Description: "Schedule recurring patch reporting"
      ScheduleExpression: "rate(10 days)"
      State: "ENABLED"
      Targets: 
        - 
          Arn: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:automation-definition/AWS-ExportPatchReportToS3:$DEFAULT"
          Id: "AWS-SystemsManager-PatchManager-PatchReport-iwasa-patch-report"
          Input: !Sub "{\"assumeRole\":[\"arn:aws:iam::${AWS::AccountId}:role/service-role/AWS-SystemsManager-PatchSummaryExportRole\"],\"reportName\": [\"iwasa-patch-report\"],\"s3BucketName\":[\"${S3Bucket}\"],\"targets\":[\"instanceids=*\"],\"snsTopicArn\":[\"${SNSTopic}\"]}"
          RoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/service-role/AWS-EventBridge-Start-SSMAutomationRole"
      EventBusName: "default"

