AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  EMailAddress: 
    Type: String
    Description: Specifies your E-Mail for Patch Scan Report.
  ScheduleExpression:
    Type: String
    Default: "cron(10 18 ? * * *)"
    Description: "cron/rate expression by UTC"
  ReportName:
    Type: String
    Description: ""
Description: "The scheduling expression that determines when and how often the rule runs"
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-patch-report-bucket
      BucketEncryption: 
          ServerSideEncryptionConfiguration: 
            - 
              ServerSideEncryptionByDefault: 
                  SSEAlgorithm: "AES256"
              BucketKeyEnabled: false
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration: 
          Rules: 
            - 
              Id: "auto-delete"
              Status: "Enabled"
              ExpirationInDays: 400

  SNSTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      DisplayName: !Sub ${AWS::StackName}-patch-report-topic
      Subscription:
      - Endpoint: !Ref EMailAddress
        Protocol: email
      TopicName: !Sub ${AWS::StackName}-patch-report-topic

  SNSTopicPolicy:
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      Topics: 
        - !Ref SNSTopic
      PolicyDocument:
        Version: 2012-10-17
        Statement: 
        - Effect: Allow
          Principal:
            AWS: "*"
          Action:
          - SNS:GetTopicAttributes
          - SNS:SetTopicAttributes
          - SNS:AddPermission
          - SNS:RemovePermission
          - SNS:DeleteTopic
          - SNS:Subscribe
          - SNS:ListSubscriptionsByTopic
          - SNS:Publish
          - SNS:Receive
          Resource: !Ref SNSTopic
          Condition:
            StringEquals: 
              AWS:SourceOwner: !Ref AWS::AccountId

  EventsRule:
    Type: "AWS::Events::Rule"
    Properties:
      Name: !Sub AWS-SystemsManager-PatchManager-PatchReport-${AWS::StackName}
      Description: "Schedule recurring patch reporting"
      ScheduleExpression: !Ref ScheduleExpression
      State: "ENABLED"
      EventBusName: "default"
      Targets: 
        - Id: !Sub ${AWS::StackName}-patch-report-target
          Arn: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:automation-definition/AWS-ExportPatchReportToS3:$DEFAULT"
          RoleArn: !GetAtt PatchAutomationRole.Arn
          Input: !Sub | 
            {
              "assumeRole": [
                "${PatchExportRole.Arn}"
              ],
              "reportName": [
                "${ReportName}"
              ],
              "s3BucketName": [
                "${S3Bucket}"
              ],
              "targets": [
                "instanceids=*"
              ],
              "snsTopicArn": [
                "${SNSTopic}"
              ]
            }

  PatchExportRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub ${AWS::StackName}-patch-summary-export-role
      AssumeRolePolicyDocument: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"ssm.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
      MaxSessionDuration: 3600
      ManagedPolicyArns: 
        - !Ref PatchExportPolicy
      Description: "Service role for lambda to execute csv export of patch reports"

  PatchAutomationRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub ${AWS::StackName}-patch-automation-role
      AssumeRolePolicyDocument: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"events.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
      MaxSessionDuration: 3600
      ManagedPolicyArns: 
        - "arn:aws:iam::aws:policy/service-role/AmazonSSMAutomationRole"
        - !Ref PatchAutomationPolicy
      Description: "Service role for event bridge to call ssm automation on a schedule"

  PatchAutomationPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: !Sub ${AWS::StackName}-patch-automation-policy
      PolicyDocument: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Action": "ssm:StartAutomationExecution",
              "Effect": "Allow",
              "Resource": [
                "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:automation-definition/AWS-ExportPatchReportToS3:$DEFAULT"
              ]
            },
            {
              "Effect": "Allow",
              "Action": [
                "iam:PassRole"
              ],
              "Resource": "${PatchExportRole.Arn}",
              "Condition": {
                "StringLikeIfExists": {
                  "iam:PassedToService": "ssm.amazonaws.com"
                }
              }
            }
          ]
        }

  PatchExportPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: !Sub ${AWS::StackName}-patch-summary-export-policy
      PolicyDocument: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "s3:PutObject"
              ],
              "Resource": [
                "*"
              ]
            },
            {
              "Effect": "Allow",
              "Action": [
                "s3:GetBucketAcl"
              ],
              "Resource": [
                "*"
              ]
            },
            {
              "Effect": "Allow",
              "Action": [
                "sns:Publish"
              ],
              "Resource": [
                "*"
              ]
            },
            {
              "Effect": "Allow",
              "Action": [
                "ssm:DescribeInstancePatchStates",
                "ssm:DescribeInstancePatches",
                "ssm:ListComplianceItems",
                "ssm:ListResourceComplianceSummaries",
                "ssm:DescribeInstanceInformation",
                "ssm:GetInventory",
                "ec2:DescribeInstances"
              ],
              "Resource": [
                "*"
              ]
            }
          ]
        }
